#+title: Preface

In the fourth year of my civil engineer studies we had to take a compulsory subject about behavioural sciences. As almost fully qualified engineers this subject was a bit strange. There were no formulas, no mathematical models and no singular true answer to the questions. The mathematical rigour that applies to designing physical structures did not seem to apply to the world of human behaviour.

Engineers like to refer to knowledge about human behaviour as a soft skill and the mathematical models of the physical world as hard skills. The term 'soft' hides a technocratic critique, contrasting these skills with the 'hard' technical skills, which in engineering cultures signals rigor, precision, and legitimacy. The phrase "It is not rocket science" seems to suggest that the science of rockets is the pinnacle of knowledge that not many other skills can attain. In the first few years in my engineering career I quickly learned that the dreaded soft skills are perhaps those that are as important for successful project delivery as the hard skills. Most of the work undertaken by engineers goes beyond the equations and models used to solve problem, but involve working with colleagues, the community in which we work, contractors, suppliers and other people in the complex network of relations that deliver engineering projects.

My interest as such shifted and I decided to do an correspondence Bachelor of Arts and learn more about the non-material world. 

The journey from an Arts degree to a PhD in business was in fact

I wrote a dissertation about the relationship between employee behaviour and the customer experience, using water utilities as a case study. The statistical skills gained through this research helped me to eventually lead the data science function at a water utility in regional Australia.

Over the past decade I have undertaken several data projects to unearth the Voice of the Customer from our data. This book is a reflection from what I have learned over the years in dealing with this type of data.

While the industry spends a lot of resources on improving how we manage engineering data using machine learning and other advanced statistical tools, customer data is as yet not

This book is written for water professionals with some experience in analysing data who like to lern how  

The book uses a series of case studies, the data and code for which are available on the accompanying GitHub repository for this book. 
