#+title: Qualitative Data Science
#+macro:        voc /Voice of the Customer/
#+bibliography: book/voc.bib

Most available data that expresses the {{{voc}}} will be qualitative in nature. Customers can express their voice either through speech or written text and we can capture this communication through various means. We can transcribe calls from customers who reach out to the water utility to express their dissatisfaction or to manage their account. We can extract text from social media or other public channels, such as letters to editors and other earned media.

While analysing numeric survey data can yield actionable insights using traditional statistical analysis, but qualitative data analysis requires a wholly different approach. Tap water is a technical service so most professionals at these organisations have a background in the physical or biological sciences and have not been trained in accounting for qualitative data.

[soft skills section from iaas]

Relying on quantitative analysis alone can only provided a limited description of reality. The richness of the human experience does not yield to numbers. 

#+begin_quote
Not everything that counts can be counted, and not everything that can be counted counts."  [cite:@cameron_1963_infor]
#+end_quote

Analysing qualitative 

This chapter discusses the principles of qualitative analysis. The first section outlines the principles of manual methods of analysing text as used by social scientists for many decades. Understanding these methods will help

However, in our age of electronic communication the amounts of qualitative data available for analysis for exceeds what a human can comprehensively analyse. I once analysed 55 million words of customer phone transcripts. At 200 words per minute it would take about 4,500 hours to read it all, excluding any analysis. It only took about 80 hours of work to analyse these text algorithmically and extract relevant insights.

* Human Analysis
:NOTES:
- [ ] https://getthematic.com/insights/methods-of-qualitative-data-analysis
:END:

The main four qualitative data analysis methods are thematic analysis, content analysis, discourse analysis, and narrative analysis. The choice of method depends on the research goals. /Thematic Analysis/ is the most common method that focuses on pasterns and themes in a text. This method is ideal for exploring interview data and assess customer and community needs and lived experience. /Content Analysis/ systematically quantifies and categorises data to uncover patterns and trends.  This is a mixed-method approach and focuses on reviewing keywords in a text, assessing their frequency and the relationship between the terms. /Narrative Analysis/ interprets a text as a story ane explores how people make sense of their experience. This technique would be useful when investigating how financial hardship impacts the life of water utility customers. Lastly, /Discourse Analysis/ studies language in context. This method can provide insight into customers lives [cite:@flick_2009].

To extract the {{{voc}}} from a text corpus, thematic and content analysis are most suitable.

https://www.youtube.com/watch?v=meWPPepnt_Q

** Thematic Analysis
https://gradcoach.com/what-is-thematic-analysis/

** Content Analysis
This method is most closely related to the computational methods used in 
https://gradcoach.com/qualitative-content-analysis/


* Computational Analysis
** Analysing Natural Language
Most data related to the {{{voc}}} is natural language in the form of text, which is notoriously hard to analyse computationally. Human minds have evolved to process language and navigate its ambiguities and even so the meaning of spoken or written words is not always perfectly transparent. Since the early days of computing scientists have sought to codify language in algorithms.

Communicating with computers requires human to learn the abstractions on computer languages. 

One of the earliest examples of language processing is ELIZA, created by Joseph [cite/t:@weizenbaum_1966_eliza] at MIT. ELIZA was able to simulate conversation using pattern matching and word substitution creating the illusion that the program understands the input. The most famous implementation of this program was a script that simulates a psychotherapist. In the 1980s the computer world was introduced to text adventures


Examples of electronic files that express the {{{voc}}} are transcripts of phone calls, chat messages, social media, reviews, newspaper articles, and any other electric means. This raw data is easily accessible through an Application Programming Interface (API). Textual data is available in different formats, such as flat text (TXT or JSON files). Text files that include formatting (PDF or word processor formats) easily convert to plain text files with Open Source tools such as Pandoc.

But machines cannot process natural language in its raw form to provide insights. Analysing texts with machines is essentially a mixed method approach. To qualitatively analyse natural language we first need to convert it to a method that enabled computation and convert a text into a set of numbers. Chapter [[#chap-text]] discusses three methods exist to achieve this goal. After the numeric representation of the text has been analysed we then need to qualitatively assess the output to provide it with meaning.



** Natural Language Processing

Content analysis

** Machine learning

** Large Language Models
Large Language Models (LLM) have revolutionised how we understand language computationally.

While it might seem that anyone can use an LLM to extract meaning from a corpus of text, knowledge of 

When asking an LLM to analyse a text file, the system will most likely write a Python script to analyse the data using the same techniques described in this book.

** Triangulation

The following chapters describe the basic techniques to algorithmically extract insights from qualitative data.
